# Generated by Django 5.1.7 on 2025-06-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pft', '0002_subscriptionplan_analyticsreport_billreminder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billreminder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='debtaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='debtpayment',
            name='debt_account',
        ),
        migrations.RemoveField(
            model_name='debtpayment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='investmentvalue',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnalyticsReport',
        ),
        migrations.DeleteModel(
            name='BillReminder',
        ),
        migrations.DeleteModel(
            name='DebtAccount',
        ),
        migrations.DeleteModel(
            name='DebtPayment',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='InvestmentValue',
        ),
        migrations.DeleteModel(
            name='SavingsGoal',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
